Sprint 4
SShliakhin/Practicum-ios_MovieQuiz pull request #2
Opened 2022-10-18 14:23 UTC by SShliakhin

# Чек лист

- [x] Приложение запускается.
- [x] Элементы интерфейса адаптируются под разрешения экранов iPhone, начиная с 13 — вёрстка под SE и iPad не предусмотрена.
- [x] Свёрстанный экран полностью соответствует макету — использованы верные шрифты нужных размеров, все надписи находятся на нужном месте, расположение всех элементов, размеры кнопок и отступы — точно такие же, как в макете.
- [x] Interface Builder не показывает ошибок с констрейнтами.
- [x] Логика приложения соответствуют функциональным и техническим требованиям, каждый пункт выполнен, и выполнен верно:
    - При запуске приложения показывается сплеш-скрин;
    - После запуска приложения показывается экран вопроса с текстом вопроса, картинкой и двумя вариантами ответа, «Да» и «Нет», только один из них правильный;
    - Вопрос квиза составляется относительно IMDb рейтинга фильма по 10-балльной шкале, например: «Рейтинг этого фильма больше 6?»;
    - Можно нажать на один из вариантов ответа на вопрос и получить отклик о том, правильный он или нет, при этом рамка фотографии поменяет цвет на соответствующий;
    - После выбора ответа на вопрос через 1 секунду автоматически появляется следующий вопрос;
    - После завершения раунда из 10 вопросов появляется алерт «Раунд окончен» с результатом текущего раунда (количество правильных ответов из 10 вопросов) и возможностью сыграть ещё раз (остальная статистика и невозможность загрузить данные реализуются в следующих спринтах);
    - Пользователь может запустить новый раунд, нажав в алерте на кнопку «Сыграть ещё раз»;

- [x] Весь код написан в одном файле MovieQuizViewController.swift.

- [x] Ваши функции и переменные приватны, не видны за пределами MovieQuizViewController.

- [x] Имена ваших переменных и функций отражают то, чем эти переменные и функции занимаются.

- [x] Вы убрали строчку sleep(3), чтобы приложение не задерживало отображение приветственного экрана на 3 секунды.

2022-10-18 22:10 UTC, mmbabaev requested changes

2022-10-18 22:10 UTC, mmbabaev commented on MovieQuiz/Helpers/UIColor+Extensions.swift
> +    static var ypBlack: UIColor { UIColor(named: "black")! }
это мелочь, но можно сделать `let`, чтобы не создавать каждый раз UIColor

2022-10-18 22:10 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func show() {
предложение: `showCurrentQuestion`?

2022-10-18 22:10 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        setPreviewImageViewBorder(width: Theme.imageAnswerBorderWidht, color: color)
понравилось, что вынесли константу

2022-10-18 22:10 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +final class Theme {
обычно делают enum, тк мы не сможем создать инстанс `Theme()`

2022-10-18 22:10 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        applyStyleAnswerButton(for: yesButton, title: "Да")
понравилась декомпозиция на функции

2022-10-18 22:10 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { // запускаем задачу через 1 секунду
Если быстро нажимать одну и ту же кнопку, то срабатывают лишние нажатия, пока мы ожидаем следующего вопроса. Чтобы этого не было, можно использовать свойство isEnabled. При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-10-18 22:11 UTC, mmbabaev commented
хорошо, что умеете верстать кодом

2022-10-18 23:36 UTC, SShliakhin commented on MovieQuiz/Helpers/UIColor+Extensions.swift
> +    static var ypBlack: UIColor { UIColor(named: "black")! }
свойство вычисляемое, компилятор не дает)

2022-10-18 23:41 UTC, SShliakhin commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +final class Theme {
Есть какая-нибудь ссылка на мастер-класс по оформлению констант: темы, констрейнты и прочее?

2022-10-19 00:03 UTC, SShliakhin commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { // запускаем задачу через 1 секунду
То же это заметил, но не знал, что делать. Спасибо!

2022-10-19 06:58 UTC, mmbabaev approved these changes

2022-10-19 06:58 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +final class Theme {
Какой-то определенной статьи не посоветую, гуглите `global constants swift`. 
То, как вы сделали - нормально. Какие еще варианты есть и что еще можно сделать: 
1) Разделить константы на приватные для файла и глобальные
2) В глобальных константах для `UIFont` бывает удобно добавлять константы через extension, как вы делали c `UIColor`
3) Делать вложенные enum. например
```
enum Constants {
   enum Fonts {
      .....
   }

   enum Layout { ... }
}
```

2022-10-19 06:58 UTC, mmbabaev commented on MovieQuiz/Helpers/UIColor+Extensions.swift
> +    static var ypBlack: UIColor { UIColor(named: "black")! }
```
extension UIColor {
   static let ypBlack = UIColor(named: "black")!
}
```

2022-10-19 13:32 UTC, SShliakhin commented on MovieQuiz/Helpers/UIColor+Extensions.swift
> +    static var ypBlack: UIColor { UIColor(named: "black")! }
почему же в учебнике дают вариант с вычисляемым свойством?

2022-10-19 14:36 UTC, mmbabaev commented on MovieQuiz/Helpers/UIColor+Extensions.swift
> +    static var ypBlack: UIColor { UIColor(named: "black")! }
это все-таки мелочь и вопрос вкуса. Можете сделать и так, и так. Можно изучить обсуждение по теме: 
https://forums.swift.org/t/static-computed-property-vs-static-let-constant/20968

2022-10-19 18:10 UTC, merged

2022-11-11 10:13 UTC, SShliakhin commented
# История ревью
Замечательная работа, давайте только поправим момент с выключением кнопок. Оставил комментарии в реквесте.

## Задачи
- [X] После выбора ответа, необходимо отключить кнопки

2022-11-11 10:14 UTC, SShliakhin commented
# История ревью
Все хорошо, работу принял