Sprint 7: MVP & Tests
SShliakhin/Practicum-ios_MovieQuiz pull request #7
Opened 2022-12-15 12:02 UTC by SShliakhin

## Написаны и проходят unit-тесты:
* На сабскрипт для безопасного получения элемента массива по индексу (ArrayTests);
* На сервис MoviesLoader (для проверки успешной загрузки и для проверки ошибки MoviesLoaderTests).
## Написаны и проходят UI-тесты:
* Два теста на замену одного постера на другой при нажатии кнопки ответа
    - Тест кнопки Да (при нажатии на кнопку Да меняется лейбл с номером вопроса).
    - Тест кнопки Нет (при нажатии на кнопку Нет меняется лейбл с номером вопроса).
* Тест появления алерта при окончании раунда 
    - алерт появился, протестировать текст на кнопке и в заголовке алерта
    - нажата кнопка на алерте
    - алерт исчез
    - счётчик вопросов сбросился к значению 1/10
## Проведён рефакторинг проекта — отрефакторен MovieQuizViewController на архитектуру MVP
- Написан и проходит тест для convert(model: QuizQuestion) -> QuizStepViewModel.

2022-12-16 12:04 UTC, ABashkirova requested changes

2022-12-16 12:04 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    init (viewController: UIViewController) {
код слипся, давай разобьем одной пустой строкой

2022-12-16 12:04 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        }
не очень красиво выглядят большие куски кода, особенно с дополнительной вложенностью в didSet

предлагаю чтобы этого избежать – вынести весь блок в приватную функцию, и вызывать здесь ее

2022-12-16 12:04 UTC, ABashkirova commented on MovieQuizTests/MovieQuizTests.swift
> +        return num1 - num2
эти тесты тренировочные, их стоило оставить в тренировочной ветке, а здесь стоит удалить, потому что проекту они пользы не несут

2022-12-16 12:04 UTC, ABashkirova commented on MovieQuizUITests/MovieQuizUITestsLaunchTests.swift
> +
давай удалим этот тестовый набор, потому что он тоже не несет пользы

2022-12-16 12:04 UTC, ABashkirova commented on MovieQuizUITests/MovieQuizUITests.swift
> +        XCTAssertTrue(indexLabel.label == "1/10")
по заданию, ожидается что ты добавишь не просто две разные проверки, а два разных теста

это поведение нужно доработать

2022-12-16 12:41 UTC, SShliakhin commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    init (viewController: UIViewController) {
Согласен, так будет понятнее. 
Пошел еще дальше, соответствие протоколу в отдельном расширении.

2022-12-16 13:26 UTC, SShliakhin commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        }
Сделано!
Мучают сомнения, код в VC
```swift
func prepareLoadQuestion() {
        activityIndicator.startAnimating()
        setPreviewImageViewBorder()
        previewImageView.flipOver()
    }
```
он содержит логику? Должен/может ли VC запускать анимацию? 
Нужно ли было разбивать на более мелкие методы и управлять через презентер?

Надо было сразу передавать цвет, или такой уровень логики допускается?
```swift
func showAnswerResult(isCorrect: Bool) {
        let color = isCorrect ? UIColor.ypGreen.cgColor : UIColor.ypRed.cgColor
        setPreviewImageViewBorder(width: Theme.imageAnswerBorderWidht, color: color)
        
        [noButton, yesButton].forEach { $0.isEnabled = false }
    }
```

2022-12-16 13:31 UTC, SShliakhin commented on MovieQuizTests/MovieQuizTests.swift
> +        return num1 - num2
Сделано!

2022-12-16 13:31 UTC, SShliakhin commented on MovieQuizUITests/MovieQuizUITestsLaunchTests.swift
> +
Сделано!

2022-12-16 13:40 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        }
> он содержит логику? Должен/может ли VC запускать анимацию? 

да по идее все действия нужны чтобы подготовиться к переходу, тут все ок

> Надо было сразу передавать цвет, или такой уровень логики допускается?

определение цвета в целом можно оставить на вью контроллере, моделью данных здесь является isCorrect, представлением - цвет

2022-12-16 14:04 UTC, SShliakhin commented on MovieQuizUITests/MovieQuizUITests.swift
> +        XCTAssertTrue(indexLabel.label == "1/10")
Разбил тест на два, мне очень понравились твои аргументы)!

2022-12-16 14:15 UTC, SShliakhin commented
Спасибо за ревью, как всегда ясно и по делу!
Есть два доп вопроса:
1. Я задумываюсь о readme.md, пока к единому стандарту не пришел, если есть образец для подражания, то приму с удовольствием.
2. Стоит ли задуматься о переименовании части свойств и методов, с развитием проекта, кажется, местами сместились акценты?

2022-12-16 14:50 UTC, ABashkirova commented
> Я задумываюсь о readme.md, пока к единому стандарту не пришел, если есть образец для подражания, то приму с удовольствием.

для тестового проекта хорошо оставить требования к реализации проекта, ссылки на макеты 
приложить итоговый результат гифкой или видео
Также иногда оставляют окружение, на котором писалось (Xcode такой-то версии + свифт), но это излишне для iOS
Если проект со сложными зависимостями (pod, carthage) - еще оставляют инструкцию как предварительно запустить

> Стоит ли задуматься о переименовании части свойств и методов, с развитием проекта, кажется, местами сместились акценты?

если хочется, то нейминг можно поправить, да, не везде хороший получился

2022-12-16 16:10 UTC, SShliakhin commented
Большое спасибо за советы!

2022-12-17 13:27 UTC, SShliakhin commented
## Комментарий с платформы:
Отлично, теперь я бы сказала, что заказчик будет счастлив – все требования выполнены :) работа принята.
🎉 Поздравляю! Ты проделал большой путь, впереди еще столько интересного! Проект получился очень аккуратным, пожалуйста, продолжай в том же духе.

2022-12-17 13:29 UTC, merged